### ISSUE TITLE
%I[] notation parser error

### ISSUE THREAD

**Issue by Val** [DamirSvrtan/fasterer#45]
I seems there is a bug in support for interpolated array of symbols separated by whitespace (Ruby > 2.X)

### `test.rb` file:
```Ruby
#!/usr/bin/env ruby

puts %I[#{42}].inspect
```

Code works:
```Shell
> ruby --version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
> ruby test.rb 
[:"42"]
```

### `fasterer` parser error:
```Shell
> fasterer test.rb
~/.gem/ruby/2.4.2/gems/ruby_parser-3.10.1/lib/ruby_parser_extras.rb:23:in `debug20': not yet 24 nil => nil (RuntimeError)
	from ~/.gem/ruby/2.4.2/gems/ruby_parser-3.10.1/lib/ruby_parser_extras.rb:883:in `new_symbol_list_entry'
	from ~/.gem/ruby/2.4.2/gems/ruby_parser-3.10.1/lib/ruby24_parser.rb:5950:in `_reduce_467'
	from ~/.rubies/ruby-2.4.2/lib/ruby/2.4.0/racc/parser.rb:259:in `_racc_do_parse_c'
	from ~/.rubies/ruby-2.4.2/lib/ruby/2.4.0/racc/parser.rb:259:in `do_parse'
	from ~/.gem/ruby/2.4.2/gems/ruby_parser-3.10.1/lib/ruby_parser_extras.rb:1087:in `block in process'
	from ~/.rubies/ruby-2.4.2/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
	from ~/.rubies/ruby-2.4.2/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
	from ~/.rubies/ruby-2.4.2/lib/ruby/2.4.0/timeout.rb:33:in `catch'
	from ~/.rubies/ruby-2.4.2/lib/ruby/2.4.0/timeout.rb:33:in `catch'
	from ~/.rubies/ruby-2.4.2/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
	from ~/.gem/ruby/2.4.2/gems/ruby_parser-3.10.1/lib/ruby_parser_extras.rb:1075:in `process'
	from ~/.gem/ruby/2.4.2/gems/fasterer-0.3.2/lib/fasterer/parser.rb:8:in `parse'
	from ~/.gem/ruby/2.4.2/gems/fasterer-0.3.2/lib/fasterer/analyzer.rb:21:in `scan'
	from ~/.gem/ruby/2.4.2/gems/fasterer-0.3.2/lib/fasterer/file_traverser.rb:57:in `scan_file'
	from ~/.gem/ruby/2.4.2/gems/fasterer-0.3.2/lib/fasterer/file_traverser.rb:49:in `block in traverse_files'
	from ~/.gem/ruby/2.4.2/gems/fasterer-0.3.2/lib/fasterer/file_traverser.rb:49:in `each'
	from ~/.gem/ruby/2.4.2/gems/fasterer-0.3.2/lib/fasterer/file_traverser.rb:49:in `traverse_files'
	from ~/.gem/ruby/2.4.2/gems/fasterer-0.3.2/lib/fasterer/file_traverser.rb:26:in `traverse'
	from ~/.gem/ruby/2.4.2/gems/fasterer-0.3.2/lib/fasterer/cli.rb:7:in `execute'
	from ~/.gem/ruby/2.4.2/gems/fasterer-0.3.2/bin/fasterer:5:in `<top (required)>'
	from ~/.gem/ruby/2.4.2/bin/fasterer:23:in `load'
	from ~/.gem/ruby/2.4.2/bin/fasterer:23:in `<main>'
```

**Comment by DamirSvrtan** [comment]
Hey @Val, thank you for reporting this issue, will look at it!

**Comment by DamirSvrtan** [comment]
Hi @Val, this issue seems related to the https://github.com/seattlerb/ruby_parser gem and not to fasterer. Could you please open up an issue over there to resolve it?

Thank you!
