### ISSUE TITLE
Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by mensfeld** [DamirSvrtan/fasterer#72]
when running fasterer I get:

```
bundler: failed to load command: fasterer (/home/mencio/.rbenv/versions/2.6.5/bin/fasterer)
Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
  gems/ruby_parser-3.14.0/lib/ruby_lexer.rex.rb:163:in `gsub'
  gems/ruby_parser-3.14.0/lib/ruby_lexer.rex.rb:163:in `block in next_token'
  gems/ruby_parser-3.14.0/lib/ruby_lexer.rex.rb:68:in `action'
  gems/ruby_parser-3.14.0/lib/ruby_lexer.rex.rb:163:in `next_token'
  gems/ruby_parser-3.14.0/lib/ruby_parser_extras.rb:1266:in `next_token'
  /home/mencio/.rbenv/versions/2.6.5/lib/ruby/2.6.0/racc/parser.rb:259:in `_racc_do_parse_c'
  /home/mencio/.rbenv/versions/2.6.5/lib/ruby/2.6.0/racc/parser.rb:259:in `do_parse'
  gems/ruby_parser-3.14.0/lib/ruby_parser_extras.rb:1301:in `block in process'
  /home/mencio/.rbenv/versions/2.6.5/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
  /home/mencio/.rbenv/versions/2.6.5/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
  /home/mencio/.rbenv/versions/2.6.5/lib/ruby/2.6.0/timeout.rb:33:in `catch'
  /home/mencio/.rbenv/versions/2.6.5/lib/ruby/2.6.0/timeout.rb:33:in `catch'
  /home/mencio/.rbenv/versions/2.6.5/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
  gems/ruby_parser-3.14.0/lib/ruby_parser_extras.rb:1289:in `process'
  gems/fasterer-0.7.1/lib/fasterer/parser.rb:8:in `parse'
  gems/fasterer-0.7.1/lib/fasterer/analyzer.rb:21:in `scan'
  gems/fasterer-0.7.1/lib/fasterer/file_traverser.rb:57:in `scan_file'
  gems/fasterer-0.7.1/lib/fasterer/file_traverser.rb:49:in `block in traverse_files'
  gems/fasterer-0.7.1/lib/fasterer/file_traverser.rb:49:in `each'
  gems/fasterer-0.7.1/lib/fasterer/file_traverser.rb:49:in `traverse_files'
  gems/fasterer-0.7.1/lib/fasterer/file_traverser.rb:26:in `traverse'
  gems/fasterer-0.7.1/lib/fasterer/cli.rb:7:in `execute'
  gems/fasterer-0.7.1/bin/fasterer:5:in `<top (required)>'
  /home/mencio/.rbenv/versions/2.6.5/bin/fasterer:23:in `load'
  /home/mencio/.rbenv/versions/2.6.5/bin/fasterer:23:in `<top (required)>'
```

repro:

```
git clone https://github.com/mensfeld/broken-fasterer.git
cd broken-fasterer
./run.sh
```

**Comment by DamirSvrtan** [comment]
Hi @mensfeld, thanks for opening the issue and I'm sorry you're seeing this. Unfortunately this is not an issue on Fasterer but the underlying parser implementation [ruby_parser](https://github.com/seattlerb/ruby_parser). Do you mind opening an issue there?

**Comment by mensfeld** [comment]
Closing in favor of https://github.com/seattlerb/ruby_parser/issues/302
